spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SchoolAnywr1?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
